#!/bin/bash

# arguments, in order:
#   - module ID (i.e. mNNN)
#   - genome accession

mkdir -p data/$1_results/blast

if [ -f "data/$1_results/blast/$1_$2_blast_results.tsv" ]; then
  echo "Found existing blast results"
else
  python3 needle/blast-genome.py data/$1_query.faa $2 data/$1_results/blast/$1_$2_blast_results.tsv --min-word-size 2
fi

echo "Collating search results"
PYTHONPATH=. python3 scripts/export-protein-results.py data/$1_query.faa ncbi-downloads/ncbi_dataset/data/$2/$2*.fna data/$1_results/blast/$1_$2_blast_results.tsv kegg-downloads/profiles $2 data/$1_results
